name: pre-commit

on:
  [push, pull_request]

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.0
