name: Unit test

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  python_test:
    name: py-unittest
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests to generate coverage statistics
        run: |
          pytest --cov --cov-report xml:py_coverage.xml
      - name: Upload coverage reports to Codecov
        if: matrix.python-version == '3.11'
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage reports as artifact
        uses: actions/upload-artifact@v4
        if: matrix.python-version == '3.11'
        with:
          name: python-coverage
          path: ./py_coverage.xml

  python_test_windows:
    name: py-unittest-windows
    runs-on: windows-latest

    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests to generate coverage statistics
        run: |
          pytest --cov --cov-report xml:py_coverage.xml
